### ISSUE TITLE
Pagination records 

### ISSUE THREAD

**Issue by hiteshi-trivedi** [apigrate/autotask-restapi#15]
can someone please help me find how I can get result if data is stored in another page due to pagination results ?

Right no I'm querying all servicecalls. I'm getting 500 records only and the nextpage url where remaining servicecalls are present.

How can I query the 2nd page for data ?

**Comment by czkoudy** [comment]
Hi @hiteshi-trivedi ,

i have accomplished this the following way:

```
router.get('/config-items', async (req, res) => {
  const api = await autotask.api();
  let nextPage = false;
  let lastID = 0;
  const configItemsAll = [];

  do {
    const result = await api.ConfigurationItems.query({
      filter: [
        {
          op: 'gte',
          field: 'id',
          value: lastID,
        },
      ],
    });
    if (result.pageDetails.nextPageUrl) {
      configItemsAll.push(...result.items);
      nextPage = true;
      lastID = result.items[result.items.length - 1].id;
    } else {
      configItemsAll.push(...result.items);
      nextPage = false;
      lastID = null;
    }
  } while (nextPage);

  if (!nextPage) {
    return res.status(200).json({ success: true, data: configItemsAll  });
  }
});
```

Hope that helps :-)

**Comment by gaumeister** [comment]
While the [Autotask API documentation](https://ww3.autotask.net/help/DeveloperHelp/Content/APIs/REST/API_Calls/REST_Advanced_Query_Features.htm#Paginati) does include some info about pagination instructions, I have also found it easier to use the id parameter querying as @czkoudy has demonstrated. 

Remember that other attributes (besides the `id` field) of your query filter should remain invariant when getting subsequent pages.

**Comment by iamexe** [comment]
Hi @czkoudy,

thank you for this solution. I am using it as well now.

There's a small mistake.

It should be (op: 'gt',) and not op: 'gte'. 

Else you will have the 500th asset twice in your configItemsAll.

Cheers!
