### ISSUE TITLE
Issues with Node v18.13.0

### ISSUE THREAD

**Issue by tmidthjell** [apigrate/autotask-restapi#17]
I'm having issues with Node v18:
FetchError: request to https://webservices.autotask.net....
failed, reason: write EPROTO DCB00000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:9

The issue seems to be related to Autotask API not using Secure Renegotiations in their SSL Certificate

**Comment by gaumeister** [comment]
I can reproduce this on node v18.13.0 also. I am looking for node environment switches to disable validation, but haven't found anything yet. Ultimately, the root cause (SSL at Autotask) should be addressed.

**Comment by gaumeister** [comment]
@tmidthjell please install latest @apigrate/autotask-restapi@0.6.2

I found and tested a workaround that allows SSL legacy renegotiation. Tested on all active node LTS versions (14, 16, 18).

**Comment by tmidthjell** [comment]
Thanks @gaumeister! I've also informed Datto Support / Sec Team about the issue. Hopefully they'll fix the potential security issue.
