### ISSUE TITLE
Handle the message for "Invalid Credentials" when encountering a 401 error.

### ISSUE THREAD

**Issue by devtushar** [apigrate/autotask-restapi#19]
When invalid credentials are used, I want to receive a message indicating either "Something is Wrong" or "Unauthorized." Currently, I'm not receiving any indication or return values that inform me the credentials are incorrect.

Is there any way to handle this ?

**Comment by gaumeister** [comment]
See 1.0.0 release, just dropped today. It includes an error-handling class you can use to catch Autotask REST API errors and handle specific error cases that way. You can get the HTTP status as well as the HTTP response body-typically something like:

```json
{ "errors":["Something went wrong"]}
```

Please keep in mind that the Autotask REST API doesn't behave in ways you might expect. For example:
- if you enter an invalid username, you'll get back an HTTP 500 status code, not a 401. 
- if you enter a valid username, but an invalid password, you'll get back an HTTP 401 error code
- if you enter valid credentials, but an invalid integration code, you'll get back an HTTP 500 status code, not a 401.
