### ISSUE TITLE
Error : Zone Information request to https://webservices.autotask.net/ATServices Rest/V1.0/zoneInformation?user=someuser%40dxfferent12345.nl failed, reason: socket hang up

### ISSUE THREAD

**Issue by devtushar** [apigrate/autotask-restapi#22]
**Describe the bug**
We are getting this error not frequently, But some times for the Zone Information , 
request to https://webservices.autotask.net/ATServices Rest/V1.0/zoneInformation?user=someuser%40dxfferent12345.nl failed, reason: socket hang up

**To Reproduce**
We are just executing any API services of Autotask and getting this error randomly, I don't have exact steps to reproduce it but, I got this error once, and when I tried to reproduce it, It is working Fine. But In our system, We are logging each error of Autotask and we got this one issue. and noticed that It is executed in package for some scenarios.

**Expected behavior**
What we want that we need to prevent this type of issue , So Please guide us further ahead to prevent this type of issue, If you have any specific guidelines.

**Environment Context:**
 - NodeJS 18

**Comment by gaumeister** [comment]
Socket hang up almost always indicates either the server dropped the connection or some other network condition caused the connection to drop. Recommend checking with Autotask. Given the sporadic nature of this issue, it is unlikely a code issue. If you can give more specific ways to reproduce it, please reopen.
