### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by eltyBelgium** [apigrate/autotask-restapi#24]
**Is your feature request related to a problem? Please describe.**

The posability to send paging in the request for getting results. Like getting all companies is now not really possible through the lib only. 

**Describe the solution you'd like**

Send paging object through the request. 

**Describe alternatives you've considered**
Custom api writing

**Comment by gaumeister** [comment]
When I've needed to implement paging, I've had more success using queries instead. 

> If your query is likely to return more records than the number set as the MaxRecords value, and you want to receive all of those records, you can create looping queries as an alternative to pagination controls. Set up queries where each query filters for an id value that is greater than the maximum value received in the previous query.

Reference: [Autotask Rest API Developer Documentation - Pagination](https://ww1.autotask.net/help/DeveloperHelp/Content/APIs/REST/API_Calls/REST_Advanced_Query_Features.htm#Paginati).
