### ISSUE TITLE
Types for typescript usage

### ISSUE THREAD

**Issue by eltyBelgium** [apigrate/autotask-restapi#25]
**Is your feature request related to a problem? Please describe.**
I use this lib in a typescript env. But there are no types for this lib sadly enough. 
would be nice to have it. 

**Describe the solution you'd like**
Types for typescript

**Comment by gaumeister** [comment]
This is not a high priority at this time. VSCode does a pretty good job autocompleting from the JSDoc included with the javascript, and there is a lot of documentation already for each method. That said, if there is something specific you need more help with, let me know.
